Insert into CAPTIVE_PORTAL.PLAN_INFO (ID_PLAN,ID_CATALOG,PLAN_NAME,PLAN_DESCRIPTION,ID_PLAN_TYPE,ENTITLEMENT,FIELD_NAME,ASSIGNED_QUOTA,QUOTA_NAME,PRICE,CURRENCY,UPLINK,DOWNLINK,SALES_GROUP,CLIENT_TYPE,IMAGE_PLAN_INFO,PLAN_FUP,UPLINK_FUP,DOWNLINK_FUP,DATE_CREATED,DATE_MODIFIED) 
values (14227,104,'Addon 500 MB',null,3,'1385564240','Entitlement',500,'C_Data_Add',null,1,null,null,4,3,null,0,null,null,to_date('20160511164027','YYYYMMDDHH24MISS'),null);

Insert into CAPTIVE_PORTAL.PLAN_INFO (ID_PLAN,ID_CATALOG,PLAN_NAME,PLAN_DESCRIPTION,ID_PLAN_TYPE,ENTITLEMENT,FIELD_NAME,ASSIGNED_QUOTA,QUOTA_NAME,PRICE,CURRENCY,UPLINK,DOWNLINK,SALES_GROUP,CLIENT_TYPE,IMAGE_PLAN_INFO,PLAN_FUP,UPLINK_FUP,DOWNLINK_FUP,DATE_CREATED,DATE_MODIFIED) 
values (14228,105,'Addon 1GB',null,3,'1285565174','Entitlement',1024,'C_Data_Add',null,1,null,null,4,3,null,0,null,null,to_date('20160511164027','YYYYMMDDHH24MISS'),null);

Insert into CAPTIVE_PORTAL.PLAN_INFO (ID_PLAN,ID_CATALOG,PLAN_NAME,PLAN_DESCRIPTION,ID_PLAN_TYPE,ENTITLEMENT,FIELD_NAME,ASSIGNED_QUOTA,QUOTA_NAME,PRICE,CURRENCY,UPLINK,DOWNLINK,SALES_GROUP,CLIENT_TYPE,IMAGE_PLAN_INFO,PLAN_FUP,UPLINK_FUP,DOWNLINK_FUP,DATE_CREATED,DATE_MODIFIED) 
values (14229,106,'Addon 2GB',null,3,'1185565359','Entitlement',2048,'C_Data_Add',null,1,null,null,4,3,null,0,null,null,to_date('20160511164027','YYYYMMDDHH24MISS'),null);

Insert into CAPTIVE_PORTAL.PLAN_INFO (ID_PLAN,ID_CATALOG,PLAN_NAME,PLAN_DESCRIPTION,ID_PLAN_TYPE,ENTITLEMENT,FIELD_NAME,ASSIGNED_QUOTA,QUOTA_NAME,PRICE,CURRENCY,UPLINK,DOWNLINK,SALES_GROUP,CLIENT_TYPE,IMAGE_PLAN_INFO,PLAN_FUP,UPLINK_FUP,DOWNLINK_FUP,DATE_CREATED,DATE_MODIFIED) 
values (14230,426,'Addon 5GB',null,3,'1985565468','Entitlement',5120,'C_Data_Add',null,1,null,null,4,3,null,0,null,null,to_date('20160511164027','YYYYMMDDHH24MISS'),null);

Insert into CAPTIVE_PORTAL.PLAN_INFO (ID_PLAN,ID_CATALOG,PLAN_NAME,PLAN_DESCRIPTION,ID_PLAN_TYPE,ENTITLEMENT,FIELD_NAME,ASSIGNED_QUOTA,QUOTA_NAME,PRICE,CURRENCY,UPLINK,DOWNLINK,SALES_GROUP,CLIENT_TYPE,IMAGE_PLAN_INFO,PLAN_FUP,UPLINK_FUP,DOWNLINK_FUP,DATE_CREATED,DATE_MODIFIED) 
values (14231,1315,'Mas Internet Promo 1GB CO2',null,3,'792478882','Entitlement',1024,'C_Data_Add',null,1,null,null,4,3,null,0,null,null,to_date('20160511164027','YYYYMMDDHH24MISS'),null);

Insert into CAPTIVE_PORTAL.PLAN_INFO (ID_PLAN,ID_CATALOG,PLAN_NAME,PLAN_DESCRIPTION,ID_PLAN_TYPE,ENTITLEMENT,FIELD_NAME,ASSIGNED_QUOTA,QUOTA_NAME,PRICE,CURRENCY,UPLINK,DOWNLINK,SALES_GROUP,CLIENT_TYPE,IMAGE_PLAN_INFO,PLAN_FUP,UPLINK_FUP,DOWNLINK_FUP,DATE_CREATED,DATE_MODIFIED) 
values (14232,1314,'Mas Internet Promo 2.5GB CO2',null,3,'592478987','Entitlement',2560,'C_Data_Add',null,1,null,null,4,3,null,0,null,null,to_date('20160511164027','YYYYMMDDHH24MISS'),null);

commit;