Insert into CAPTIVE_PORTAL.PLAN_INFO (ID_PLAN,ID_CATALOG,PLAN_NAME,PLAN_DESCRIPTION,ID_PLAN_TYPE,ENTITLEMENT,FIELD_NAME,ASSIGNED_QUOTA,QUOTA_NAME,PRICE,CURRENCY,UPLINK,DOWNLINK,SALES_GROUP,CLIENT_TYPE,IMAGE_PLAN_INFO,PLAN_FUP,UPLINK_FUP,DOWNLINK_FUP,DATE_CREATED,DATE_MODIFIED) 
values (14263,0,'App Pospago Facebook',null,3,'OCS_APP_FB_POS_SY','Entitlement',2560,'FB QUOTA POSTPAID',null,1,null,null,4,3,null,0,null,null,to_date('20160511164027','YYYYMMDDHH24MISS'),null);

Insert into CAPTIVE_PORTAL.PLAN_INFO (ID_PLAN,ID_CATALOG,PLAN_NAME,PLAN_DESCRIPTION,ID_PLAN_TYPE,ENTITLEMENT,FIELD_NAME,ASSIGNED_QUOTA,QUOTA_NAME,PRICE,CURRENCY,UPLINK,DOWNLINK,SALES_GROUP,CLIENT_TYPE,IMAGE_PLAN_INFO,PLAN_FUP,UPLINK_FUP,DOWNLINK_FUP,DATE_CREATED,DATE_MODIFIED) 
values (14264,0,'App Pospago Facebook UNL',null,3,'OCS_APP_FB_UNL_POS_SY','Entitlement',2560,'FBUNL QUOTA POSTPAID',null,1,null,null,4,3,null,0,null,null,to_date('20160511164027','YYYYMMDDHH24MISS'),null);

Insert into CAPTIVE_PORTAL.PLAN_INFO (ID_PLAN,ID_CATALOG,PLAN_NAME,PLAN_DESCRIPTION,ID_PLAN_TYPE,ENTITLEMENT,FIELD_NAME,ASSIGNED_QUOTA,QUOTA_NAME,PRICE,CURRENCY,UPLINK,DOWNLINK,SALES_GROUP,CLIENT_TYPE,IMAGE_PLAN_INFO,PLAN_FUP,UPLINK_FUP,DOWNLINK_FUP,DATE_CREATED,DATE_MODIFIED) 
values (14265,0,'App Pospago Whatsapp',null,3,'OCS_APP_WA_POS_SY','Entitlement',2560,'WS QUOTA POSTPAID',null,1,null,null,4,3,null,0,null,null,to_date('20160511164027','YYYYMMDDHH24MISS'),null);

Insert into CAPTIVE_PORTAL.PLAN_INFO (ID_PLAN,ID_CATALOG,PLAN_NAME,PLAN_DESCRIPTION,ID_PLAN_TYPE,ENTITLEMENT,FIELD_NAME,ASSIGNED_QUOTA,QUOTA_NAME,PRICE,CURRENCY,UPLINK,DOWNLINK,SALES_GROUP,CLIENT_TYPE,IMAGE_PLAN_INFO,PLAN_FUP,UPLINK_FUP,DOWNLINK_FUP,DATE_CREATED,DATE_MODIFIED) 
values (14266,0,'App Pospago Whatsapp UNL',null,3,'OCS_APP_WA_UNL_POS_SY','Entitlement',2560,'WSUNL QUOTA POSTPAID',null,1,null,null,4,3,null,0,null,null,to_date('20160511164027','YYYYMMDDHH24MISS'),null);

Insert into CAPTIVE_PORTAL.PLAN_INFO (ID_PLAN,ID_CATALOG,PLAN_NAME,PLAN_DESCRIPTION,ID_PLAN_TYPE,ENTITLEMENT,FIELD_NAME,ASSIGNED_QUOTA,QUOTA_NAME,PRICE,CURRENCY,UPLINK,DOWNLINK,SALES_GROUP,CLIENT_TYPE,IMAGE_PLAN_INFO,PLAN_FUP,UPLINK_FUP,DOWNLINK_FUP,DATE_CREATED,DATE_MODIFIED) 
values (14267,0,'App Pospago Deezer',null,3,'OCS_APP_DZ_POS_SY','Entitlement',2560,'DZ QUOTA POSTPAID',null,1,null,null,4,3,null,0,null,null,to_date('20160511164027','YYYYMMDDHH24MISS'),null);

Insert into CAPTIVE_PORTAL.PLAN_INFO (ID_PLAN,ID_CATALOG,PLAN_NAME,PLAN_DESCRIPTION,ID_PLAN_TYPE,ENTITLEMENT,FIELD_NAME,ASSIGNED_QUOTA,QUOTA_NAME,PRICE,CURRENCY,UPLINK,DOWNLINK,SALES_GROUP,CLIENT_TYPE,IMAGE_PLAN_INFO,PLAN_FUP,UPLINK_FUP,DOWNLINK_FUP,DATE_CREATED,DATE_MODIFIED) 
values (14268,0,'App Pospago Deezer UNL',null,3,'OCS_APP_DZ_UNL_POS_SY','Entitlement',2560,'DZUNL QUOTA POSTPAID',null,1,null,null,4,3,null,0,null,null,to_date('20160511164027','YYYYMMDDHH24MISS'),null);

commit;


update CAPTIVE_PORTAL.PLAN_INFO set ID_PLAN_TYPE=4 where ID_CATALOG in (104,105,106,426,1315,1314);
commit;